name = "MachineVision"
uuid = "BD2B86A9-2C7B-43B7-A99C-C8E13FF4402B"
authors = ["schrpe"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.5"

[targets]
test = ["Test"]
